### ISSUE TITLE
conformsTo check fails when conformsTo is an array

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ldac-profile#1]
Presumably a crate can conform to a number of profiles so this check should be able to handle an array of conformsTo objects. In the pdsc case it will only conform to one (the relevant ldaca profile) but the json tools are writing it out as an array.

**Comment by ptsefton** [comment]
I can't reproduce this as an error. Can you submit a test as a PR please.

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________
From: Marco La Rosa ***@***.***>
Sent: Tuesday, November 22, 2022 14:47
To: Language-Research-Technology/ldac-profile ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Language-Research-Technology/ldac-profile] conformsTo check fails when conformsTo is an array (Issue #1)


Presumably a crate can conform to a number of profiles so this check should be able to handle an array of conformsTo objects. In the pdsc case it will only conform to one (the relevant ldaca profile) but the json tools are writing it out as an array.

**Comment by marcolarosa** [comment]
The error seems to be at https://github.com/Language-Research-Technology/ldac-profile/blob/master/lib/rules.js#L303. It's evaluating to false. Should that be `ObjectProfileUrl`?

**Comment by ptsefton** [comment]
An RepositoryObject may have multiple conformsToURLs that's true but it CANNOT be both an object and a collection, so if you're adding CollectionProfileUrl ObjectProfileUrl then you will get an error. Saying it's a "workflow" or some other thing would be potentially fine,

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by marcolarosa** [comment]
Here's the full root dataset from my file:
```
    {
      "@id": "./",
      "@type": [
        "Dataset",
        "RepositoryObject"
      ],
      "additionalType": "item",
      "bornDigital": 0,
      "collector": {
        "@id": "http://nla.gov.au/nla.party-479603"
      },
      "contentLanguages": [
        {
          "@id": "https://glottolog.org/resource/languoid/id/bisl1239"
        },
        {
          "@id": "https://glottolog.org/resource/languoid/id/sout2856"
        }
      ],
      "countries": {
        "@id": "https://www.ethnologue.com/country/VU"
      },
      "dateCreated": "2012-09-27T10:08:00.000Z",
      "dateModified": "2019-09-25T23:52:02.000Z",
      "depositor": {
        "@id": "http://nla.gov.au/nla.party-479603"
      },
      "description": "Elicitation with Silas Alban at Eratap village, Efate. (side B) 11/10/1995. Reading a wordlist in Nafsan.",
      "digitisedOn": "Mon Jan 01 2001 00:00:00 GMT+1100 (Australian Eastern Daylight Time)",
      "external": 0,
      "hasPart": [
        {
          "@id": "NT1-001-001A.wav"
        },
        {
          "@id": "NT1-001-001B.mp3"
        },
        {
          "@id": "NT1-001-001B.wav"
        },
        {
          "@id": "NT1-001-001A.mp3"
        }
      ],
      "identifier": [
        {
          "@id": "#identifier_domain"
        },
        {
          "@id": "#identifier_id"
        },
        {
          "@id": "#identifier_hashid"
        },
        {
          "@id": "#identifier_itemId"
        },
        {
          "@id": "#identifier_collectionId"
        }
      ],
      "languageAsGiven": "Nafsan",
      "license": {
        "@id": "LICENSE.txt"
      },
      "memberOf": {
        "@id": "https://catalog.paradisec.org.au/collections/NT1"
      },
      "metadataExportable": 1,
      "name": "Elicitation with Silas Alban",
      "operator": {
        "@id": "jommij@yahoo.com"
      },
      "originalMedia": "audiocassette",
      "originatedOn": "1995-08-16",
      "private": 0,
      "publisher": {
        "@id": "http://nla.gov.au/nla.party-593909"
      },
      "recorder": {
        "@id": "http://nla.gov.au/nla.party-479603"
      },
      "speaker": {
        "@id": "#Sailas Alban"
      },
      "subjectLanguages": {
        "@id": "https://glottolog.org/resource/languoid/id/sout2856"
      },
      "tapesReturned": 0,
      "conformsTo": {
        "@id": "https://purl.archive.org/language-data-commons/profile#Object"
      },
      "datePublished": "2019-09-25T23:52:02.000Z",
      "language": [
        {
          "@id": "https://glottolog.org/resource/languoid/id/bisl1239"
        },
        {
          "@id": "https://glottolog.org/resource/languoid/id/sout2856"
        }
      ]
    },
```

`conformsTo` is 3rd from the bottom. It's defined and and it points to the correct url. I don't understand why the test is failing and I don't have any more time to give this. I'll have to leave it with you.

**Comment by ptsefton** [comment]
Can I have the whole file please?

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by marcolarosa** [comment]
File emailed.

And here's what I see on the console (i'm skipping the other tests):
```
$ npx mocha test/validator.paradisec.spec.js


  RepositoryObject
    1) can check a PARADISEC Object 1


  0 passing (12ms)
  1 failing

  1) RepositoryObject
       can check a PARADISEC Object 1:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(hasClause(result.errors, rules.RepositoryObject.conformsTo))

      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/validator.paradisec.spec.js:111:5)
      at processImmediate (node:internal/timers:466:21)


```

**Comment by ptsefton** [comment]
the assertion is asserting that there is an error being reported, if it has a valid conformsTo then there is no error so that asserting will fail

**Comment by marcolarosa** [comment]
I must be missing something about how all of this works. I'll not bother with these tests and just read the code. When I have a new set I'll send them to you for validation.
